DROP TABLE IF EXISTS business_form_data CASCADE;
DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS agent_run_logs CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS approval_tasks CASCADE;
